# Allow anonymous FTP? (Beware - allowed by default if you comment this out).
anonymous_enable=YES

# Uncomment this to allow local users to log in.
local_enable=YES

# Uncomment this to enable any form of FTP write command.
write_enable=YES

# Default umask for local users is 077.
# local_umask sets default mode.
# for example,
#folder : 777 - 022 = 755
#file : 666 - 022 = 644
local_umask=022

# Activate directory messages - messages given to remote users when they
# go into a certain directory.
dirmessage_enable=YES

# Activate logging of uploads/downloads.
xferlog_enable=YES

# Make sure PORT transfer connections originate from port 20 (ftp-data).
connect_from_port_20=YES

# If you wan
t, you can arrange for uploaded anonymous files to be owned by
# a different user. Note! Using "root" for uploaded files is not
# recommended!
chown_username=ekim

# You may override where the log file goes if you like. The default is shown
# below.
xferlog_file=/var/log/vsftpd.log

# You may fully customise the login banner string:
ftpd_banner=Welcome to blah FTP service.

# When "listen" directive is enabled, vsftpd runs in standalone mode and
# listens on IPv4 sockets. This directive cannot be used in conjunction
# with the listen_ipv6 directive.
listen=YES

# If your version doesn't work with tcp_wrappers, add seccomp_sandbox=NO to the config.
# this option prevent ftp from 5000 error.
# from : https://www.liquidweb.com/kb/error-500-oops-priv_sock_get_cmd-on-fedora-20-solved/
seccomp_sandbox=NO

# We need to specify the location of our certificate and key files. 
# We actually combined both pieces of information into a single file, 
# so we will point both options to the same file:
rsa_cert_file=/etc/ssl/certs/vsftpd.crt
rsa_private_key_file=/etc/ssl/private/vsftpd.key

# Next, we need enable the use of these files and disable anonymous users.
# We should also force the use of SSL for both data transfer and login routines. 
# This will make the security mandatory:
ssl_enable=YES

# there are two mode : 'passive mode' and 'active mode'.
## passive mode
# pasv_address: Use this option to override the IP address that vsftpd will advertise in response 
#to the PASV command. Provide a numeric IP address, unless pasv_addr_resolve is enabled, 
#in which case you can provide a hostname which will be DNS resolved for you at startup.
#Default: (none - the address is taken from the incoming connected socket)
# from : http://vsftpd.beasts.org/vsftpd_conf.html
pasv_enable=YES
# pasv_addr_resolve=YES
# pasv_address=__MINIKUBE_IP__
pasv_min_port=50020
pasv_max_port=50021