apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: wordpress-svc
  labels:
    app: wordpress-app
spec:
  selector:
    app: wordpress
  type: LoadBalancer
  ports:
    - name: wordpress
      port: 5050
      targetPort: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-app
  template:
    metadata:
      labels:
        app: wordpress-app
    spec:
      containers:
        - name : wordpress
          image: service-wordpress
          imagePullPolicy: Never
          ports:
            - containerPort: 5050
          env:
            - name: MYSQL_IP
              value: ?