apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf
  labels:
    app: telegraf
data:
  telegraf_config: |
    [global_tags]
    [agent]
      interval = "10s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "10s"
      flush_jitter = "0s"
      precision = ""
      debug = false
      quiet = false
      logfile = ""
      hostname = ""
      omit_hostname = false

    [[outputs.influxdb]]
      urls = ["http://influxdb:8086"]
      database = "telegraf"
      retention_policy = ""
      write_consistency = "any"
      timeout = "5s"
      username = "ekim"
      password = "password"

    [[inputs.cpu]]
      percpu = false
      totalcpu = true
      collect_cpu_time = false
      report_active = false

    [[inputs.docker]]
      endpoint = "unix:///var/run/docker.sock"
      gather_services = false
      timeout = "5s"
      perdevice = true
      total = false
      docker_label_include = []

##[inputs.docker]
#endpoint : To use environment variables (ie, docker-machine), set endpoint = ENV
#timeout : Set to true to collect Swarm metrics(desired_replicas, running_replicas)
#perdevice: Timeout for docker list, info, and stats commands
## Whether to report for each container per-device blkio (8:0, 8:1...) and
## network (eth0, eth1, ...) stats or not
#total : whether to report for each container total blkio and network stats or not
#docker_label_include : docker labels to include and exclude as tags.  Globs accepted.
## Note that an empty array for both will include all labels as tags
#telegraf variable docs: https://docs.influxdata.com/telegraf/v1.14/administration/configuration/#set-environment-variables